[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/home/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[plugins]]
package = "netlify-plugin-inline-critical-css"

[plugins.inputs]
excludedPath = "/*"
